base: &base
  adapter: mysql2
  socket: /var/run/mysqld/mysqld.sock
  username: adam_www
  password: TweOgbasjow2

development:
  database: adam_www_dev
  <<: *base

test:
  database: adam_www_test
  <<: *base

